"""RFLink RX compatibility bridge. GitHub external_component; Arduino only."""
from pathlib import Path
import logging

from esphome import automation
import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.components import binary_sensor, remote_base, sensor, switch, text_sensor
from esphome.const import CONF_ID, CONF_NAME, CONF_TRIGGER_ID
from esphome.core import CORE

from .stage_sources import select_plugins, stage

DEPENDENCIES = ["remote_receiver"]
AUTO_LOAD = ["binary_sensor", "remote_base", "sensor", "switch", "text_sensor"]
MULTI_CONF = False
CODEOWNERS = []

CONF_RX_PLUGINS = "rx_plugins"
CONF_PLUGIN_PROFILE = "plugin_profile"
CONF_ON_MESSAGE = "on_message"
CONF_LOG_MESSAGES = "log_messages"
CONF_PLUGIN_SWITCHES = "plugin_switches"
CONF_ACTIVE_PLUGINS = "active_plugins"
CONF_PLUGIN_NUMBER = "_rflink_plugin_number"
CONF_UNSUPPORTED_SIGNAL = "unsupported_signal"
CONF_SIGNAL = "signal"
CONF_PULSE_COUNT = "pulse_count"
CONF_AUTO_START = "auto_start"
CONF_SETTLE_TIME = "settle_time"
CONF_DIAGNOSTICS_INTERVAL = "diagnostics_interval"
CONF_REQUIRE_NETWORK = "require_network"
CONF_REQUIRE_API = "require_api"
CONF_MONITORING = "monitoring"
CONF_DECODE_ACTIVE = "decode_active"
CONF_HEALTH = "health"
CONF_BUILD = "build"
_LOGGER = logging.getLogger(__name__)
REPO = Path(__file__).resolve().parents[2]

PLUGIN_NAMES = {
    1: "Packet preprocessor", 2: "LaCrosse v2 2300/3600", 3: "Kaku / ARC",
    4: "NewKAKU / Intertechno", 5: "Eurodomest", 6: "Blyss", 7: "Conrad RSL2",
    8: "Kambrook", 9: "X10 RF", 10: "TRC02 RGB", 11: "Home Confort",
    12: "Flamingo FA500R", 13: "Powerfix / Quigg", 14: "Ikea Koppla", 15: "Home Easy EU",
    16: "Silvercrest socket remote", 18: "Louvolite R1492-6CH-WH",
    29: "Alecto V2", 30: "Alecto V1", 31: "Alecto V3", 32: "Alecto V4",
    33: "Conrad Pool Thermometer", 34: "Cresta", 35: "Imagintronix", 36: "F007_TH",
    37: "AcuRite 986", 40: "Mebus", 41: "LaCrosse v3 WS7000", 42: "UPM / Esic",
    43: "LaCrosse v1", 44: "Auriol v3", 45: "Auriol", 46: "Auriol v2 / Xiron",
    47: "Auriol v4", 48: "Oregon V2/V3", 49: "LaCrosse TX141/TX145",
    50: "Fine Offset WH2", 60: "Ajax / Chubb / Varel", 61: "EV1527 / Chinese sensors",
    62: "Chuango", 63: "Oregon PIR / Alarm / Light", 64: "Atlantic / Visonic",
    70: "Select Plus / Quhwa", 71: "Plieger York", 72: "Byron SX", 73: "Deltronic",
    74: "RL02", 75: "Silvercrest doorbell", 76: "CAME TOP-432", 77: "Avantek",
    80: "Flamingo FA20 / KD101", 81: "Mertik Maxitrol / Dru", 82: "Mertik Maxitrol / Dru",
    83: "Brel / Dooya", 254: "Unsupported packet debug",
}

ns = cg.esphome_ns.namespace("rflink")
RFLinkComponent = ns.class_("RFLinkComponent", cg.Component, remote_base.RemoteReceiverListener)
RFLinkPluginSwitch = ns.class_("RFLinkPluginSwitch", switch.Switch, cg.Component)
RFLinkMonitoringSwitch = ns.class_("RFLinkMonitoringSwitch", switch.Switch, cg.Component)
RFLinkMessageTrigger = ns.class_("RFLinkMessageTrigger", automation.Trigger.template(cg.std_string))


def validate_plugins(value):
    if isinstance(value, str):
        selection = cv.one_of("configured", "all", lower=True)(value)
    else:
        selection = cv.ensure_list(cv.int_range(min=1, max=255))(value)
    return selection


PLUGIN_SWITCH_SCHEMA = switch.switch_schema(
    RFLinkPluginSwitch,
    default_restore_mode="RESTORE_DEFAULT_ON",
    entity_category="config",
    icon="mdi:puzzle",
).extend({
    cv.Required(CONF_PLUGIN_NUMBER): cv.int_range(min=1, max=255),
}).extend(cv.COMPONENT_SCHEMA)


def validate_plugin_switch(value):
    # v0.2.0.1 public syntax is intentionally just a list of plugin numbers:
    # plugin_switches: [30, 61, 254]
    # IDs, names and restore modes are generated by the component.
    if not (isinstance(value, int) or (isinstance(value, str) and value.strip().isdigit())):
        raise cv.Invalid("plugin_switches entries must be plugin numbers only, e.g. [30, 61, 254]")
    plugin_id = cv.int_range(min=1, max=255)(int(value))
    if plugin_id == 1:
        raise cv.Invalid("Plugin 001 is the RFLink packet preprocessor and is always enabled; do not list it.")
    return PLUGIN_SWITCH_SCHEMA({
        CONF_PLUGIN_NUMBER: plugin_id,
        CONF_NAME: f"RFLink {plugin_id:03d} · {PLUGIN_NAMES.get(plugin_id, 'Plugin')}",
    })


UNSUPPORTED_SIGNAL_SCHEMA = cv.Schema({
    cv.Optional(
        CONF_SIGNAL,
        default={CONF_NAME: "RFLink ismeretlen jel"},
    ): text_sensor.text_sensor_schema(
        entity_category="diagnostic",
        icon="mdi:waveform",
    ),
    cv.Optional(
        CONF_PULSE_COUNT,
        default={CONF_NAME: "RFLink ismeretlen jel impulzusszám"},
    ): sensor.sensor_schema(
        accuracy_decimals=0,
        entity_category="diagnostic",
        icon="mdi:counter",
    ),
})


MONITORING_SWITCH_SCHEMA = switch.switch_schema(
    RFLinkMonitoringSwitch,
    default_restore_mode="ALWAYS_ON",
    entity_category="config",
    icon="mdi:radio-tower",
).extend(cv.COMPONENT_SCHEMA)


AUTO_START_SCHEMA = cv.Schema({
    cv.Optional(CONF_SETTLE_TIME, default="5s"): cv.positive_time_period_milliseconds,
    cv.Optional(CONF_DIAGNOSTICS_INTERVAL, default="30s"): cv.positive_time_period_milliseconds,
    cv.Optional(CONF_REQUIRE_NETWORK, default=True): cv.boolean,
    cv.Optional(CONF_REQUIRE_API, default=True): cv.boolean,
    cv.Optional(
        CONF_MONITORING,
        default={CONF_NAME: "RFLink figyelés"},
    ): MONITORING_SWITCH_SCHEMA,
    cv.Optional(
        CONF_DECODE_ACTIVE,
        default={CONF_NAME: "RFLink dekódolás aktív"},
    ): binary_sensor.binary_sensor_schema(
        entity_category="diagnostic",
        icon="mdi:radio-tower",
    ),
    cv.Optional(
        CONF_HEALTH,
        default={CONF_NAME: "RFLink állapot"},
    ): text_sensor.text_sensor_schema(
        entity_category="diagnostic",
        icon="mdi:heart-pulse",
    ),
    cv.Optional(
        CONF_BUILD,
        default={CONF_NAME: "RFLink build"},
    ): text_sensor.text_sensor_schema(
        entity_category="diagnostic",
        icon="mdi:information-outline",
    ),
})


def validate_auto_start(value):
    # `auto_start: true` is the compact form. Omitting auto_start preserves
    # pre-v0.1.9 behaviour for MQTT-only/legacy external-component users.
    if value is True:
        value = {}
    elif value is False:
        return False
    if not isinstance(value, dict):
        raise cv.Invalid("auto_start must be true, false, or a mapping")
    return AUTO_START_SCHEMA(value)


PLUGIN_SWITCHES_SCHEMA = cv.All(
    cv.ensure_list(validate_plugin_switch),
    cv.Length(min=1),
)


def validate_plugin_config(config):
    try:
        compiled = select_plugins(REPO, config[CONF_RX_PLUGINS], config[CONF_PLUGIN_PROFILE])
    except (OSError, ValueError) as error:
        raise cv.Invalid(str(error)) from error
    switches = config.get(CONF_PLUGIN_SWITCHES)
    if switches:
        ids = [entry[CONF_PLUGIN_NUMBER] for entry in switches]
        if len(ids) != len(set(ids)):
            raise cv.Invalid("plugin_switches contains duplicate plugin numbers")
        missing = sorted(set(ids) - set(compiled))
        if missing:
            raise cv.Invalid("Runtime switch requested for plugin(s) not compiled: " + ", ".join(f"{n:03d}" for n in missing))
    return config


CONFIG_SCHEMA = cv.All(
    cv.Schema({
        cv.GenerateID(): cv.declare_id(RFLinkComponent),
        cv.Optional(CONF_RX_PLUGINS, default="configured"): validate_plugins,
        cv.Optional(CONF_PLUGIN_PROFILE, default="legacy"): cv.one_of("legacy", "extended", lower=True),
        cv.Optional(CONF_LOG_MESSAGES, default=True): cv.boolean,
        cv.Optional(CONF_AUTO_START): validate_auto_start,
        cv.Optional(CONF_PLUGIN_SWITCHES): PLUGIN_SWITCHES_SCHEMA,
        cv.Optional(
            CONF_ACTIVE_PLUGINS,
            default={CONF_NAME: "RFLink aktív pluginok"},
        ): text_sensor.text_sensor_schema(
            entity_category="diagnostic",
            icon="mdi:format-list-numbered",
        ),
        cv.Optional(CONF_UNSUPPORTED_SIGNAL, default={}): UNSUPPORTED_SIGNAL_SCHEMA,
        cv.Optional(CONF_ON_MESSAGE): automation.validate_automation({
            cv.GenerateID(CONF_TRIGGER_ID): cv.declare_id(RFLinkMessageTrigger),
        }),
    }).extend(remote_base.REMOTE_LISTENER_SCHEMA).extend(cv.COMPONENT_SCHEMA),
    cv.only_with_arduino,
    validate_plugin_config,
)


async def to_code(config):
    ids = stage(REPO, Path(CORE.relative_src_path("rflink_vendor")), config[CONF_RX_PLUGINS], config[CONF_PLUGIN_PROFILE])
    _LOGGER.info("RFLink profile: %s", config[CONF_PLUGIN_PROFILE])
    _LOGGER.info("RFLink RX plugins: %s; source files unchanged; TX disabled",
                 ", ".join(f"{n:03d}" for n in ids))
    var = cg.new_Pvariable(config[CONF_ID])
    await cg.register_component(var, config)
    await remote_base.register_listener(var, config)
    receiver = await cg.get_variable(config[remote_base.CONF_RECEIVER_ID])
    cg.add(var.set_receiver(receiver))
    cg.add(var.set_log_messages(config[CONF_LOG_MESSAGES]))

    auto_start = config.get(CONF_AUTO_START)
    if auto_start is not None and auto_start is not False:
        cg.add_define("USE_RFLINK_AUTO_START")
        cg.add(var.set_auto_start_enabled(True))
        cg.add(var.set_auto_start_settle_ms(auto_start[CONF_SETTLE_TIME].total_milliseconds))
        cg.add(var.set_diagnostics_interval_ms(auto_start[CONF_DIAGNOSTICS_INTERVAL].total_milliseconds))
        cg.add(var.set_require_network(auto_start[CONF_REQUIRE_NETWORK]))
        cg.add(var.set_require_api(auto_start[CONF_REQUIRE_API]))

        monitoring = cg.new_Pvariable(auto_start[CONF_MONITORING][CONF_ID], var)
        await cg.register_component(monitoring, auto_start[CONF_MONITORING])
        await switch.register_switch(monitoring, auto_start[CONF_MONITORING])

        decode_active = await binary_sensor.new_binary_sensor(auto_start[CONF_DECODE_ACTIVE])
        health = await text_sensor.new_text_sensor(auto_start[CONF_HEALTH])
        build = await text_sensor.new_text_sensor(auto_start[CONF_BUILD])
        cg.add(var.set_decode_active_sensor(decode_active))
        cg.add(var.set_health_text_sensor(health))
        cg.add(var.set_build_text_sensor(build))

    plugin_switches = config.get(CONF_PLUGIN_SWITCHES)
    cg.add(var.set_plugin_switch_mode(plugin_switches is not None))
    if plugin_switches:
        for conf in plugin_switches:
            plugin_number = conf[CONF_PLUGIN_NUMBER]
            cg.add(var.add_configured_plugin(plugin_number))
            sw = cg.new_Pvariable(conf[CONF_ID], var, plugin_number)
            await cg.register_component(sw, conf)
            await switch.register_switch(sw, conf)
            if plugin_number == 254:
                # Plugin 254 is always a temporary diagnostic fallback. It is
                # deliberately never restored ON after reboot/OTA.
                cg.add(sw.set_restore_mode(switch.RESTORE_MODES["ALWAYS_OFF"]))

        active_plugins = await text_sensor.new_text_sensor(config[CONF_ACTIVE_PLUGINS])
        cg.add(var.set_active_plugins_text_sensor(active_plugins))

        if 254 in {conf[CONF_PLUGIN_NUMBER] for conf in plugin_switches}:
            unsupported_conf = config[CONF_UNSUPPORTED_SIGNAL]
            unsupported_text = await text_sensor.new_text_sensor(unsupported_conf[CONF_SIGNAL])
            unsupported_count = await sensor.new_sensor(unsupported_conf[CONF_PULSE_COUNT])
            cg.add(var.set_unsupported_signal_text_sensor(unsupported_text))
            cg.add(var.set_unsupported_pulse_count_sensor(unsupported_count))

    for conf in config.get(CONF_ON_MESSAGE, []):
        trigger = cg.new_Pvariable(conf[CONF_TRIGGER_ID], var)
        await automation.build_automation(trigger, [(cg.std_string, "x")], conf)
